<?php

/**
 * @file
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function challenge_pages_theme() {
  return [
    'challenge_pages_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-page-theme-page',
    ],
    'challenge_subpage_module_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-subpage-theme-page',
    ],
    'challenge_news_module_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-news-theme-page',
    ],
  ];
}

/**
 * Implements hook_presave().
 */
function challenge_pages_node_presave(NodeInterface $node) {
  if ($node->getType() == 'challenge') {

    // Check for conflict on friendly url name. Must be unique.
    $friendly_url = clean_url($node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value']);
    $original_friendly_url = clean_url($node->original->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value']);

    if (get_friendly_url_name($friendly_url) and $friendly_url != $original_friendly_url) {
      $response = new RedirectResponse(\Drupal::request()->getRequestUri());
      $response->send();
      drupal_set_message(t('Friendly URL must be unique. There is already a challenge with that friendly URL'), 'error', TRUE);
      exit;
    }

    $node->set('field_friendly_url', $friendly_url);

    // Delete original paths - this may or may not do anything.
    db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url)->execute();
    db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/news')->execute();
    if ($node->getTranslation('en')->get('field_challeng_subpage_url_1')->getValue()) {
      db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_1')->getValue()[0]['value'])->execute();
    }
    if ($node->getTranslation('en')->get('field_challeng_subpage_url_2')->getValue()) {
      db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_2')->getValue()[0]['value'])->execute();
    }
    if ($node->getTranslation('en')->get('field_challeng_subpage_url_3')->getValue()) {
      db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_3')->getValue()[0]['value'])->execute();
    }
    if ($node->getTranslation('en')->get('field_challeng_subpage_url_4')->getValue()) {
      db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_4')->getValue()[0]['value'])->execute();
    }
    if ($node->getTranslation('en')->get('field_challeng_subpage_url_5')->getValue()) {
      db_delete('url_alias')->condition('source', '/challenges/' . $original_friendly_url . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_5')->getValue()[0]['value'])->execute();
    }

    // Delete any conflicting paths. Add new paths.
    db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url)->execute();
    db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/news')->execute();

    // Check if french alias already exists, if not then create.
    if ($node->getTranslation('fr')->get('field_friendly_url')->getValue()) {
      if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']))) {
        db_insert('url_alias')->fields([
          'source' => '/challenges/' . $friendly_url,
          'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'],
          'langcode' => 'fr',
        ])->execute();
      }
    };

    if ($node->getTranslation('fr')->get('field_friendly_url')->getValue()) {
      if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/nouvelles')) {
        db_insert('url_alias')->fields([
          'source' => '/challenges/' . $friendly_url . '/news',
          'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/nouvelles',
          'langcode' => 'fr',
        ])->execute();
      }
    };

    // Do the same for subpages.
    if (!empty(($node->get('field_challeng_subpage_url_1')->getValue()[0]['value'])) && ($node->get('field_challenge_subpage_enable_1')->getValue()[0]['value'])) {
      $friendly_subpage_url = clean_url($node->get('field_challeng_subpage_url_1')->getValue()[0]['value']);
      $node->set('field_challeng_subpage_url_1', $friendly_subpage_url);

      db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/' . $friendly_subpage_url)->execute();

      if ($node->getTranslation('fr')->get('field_friendly_url')->getValue() && $node->getTranslation('fr')->get('field_challeng_subpage_url_1')->getValue()) {
        if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_1')->getValue()[0]['value'])) {
          db_insert('url_alias')->fields([
            'source' => '/challenges/' . $node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_1')->getValue()[0]['value'],
            'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_1')->getValue()[0]['value'],
            'langcode' => 'fr',
          ])->execute();
        }
      };
    }
    if (!empty(($node->get('field_challeng_subpage_url_2')->getValue()[0]['value'])) && ($node->get('field_challenge_subpage_enable_2')->getValue()[0]['value'])) {
      $friendly_subpage_url = clean_url($node->get('field_challeng_subpage_url_2')->getValue()[0]['value']);
      $node->set('field_challeng_subpage_url_2', $friendly_subpage_url);

      db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/' . $friendly_subpage_url)->execute();

      if ($node->getTranslation('fr')->get('field_friendly_url')->getValue() && $node->getTranslation('fr')->get('field_challeng_subpage_url_2')->getValue()) {
        if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_2')->getValue()[0]['value'])) {
          db_insert('url_alias')->fields([
            'source' => '/challenges/' . $node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_2')->getValue()[0]['value'],
            'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_2')->getValue()[0]['value'],
            'langcode' => 'fr',
          ])->execute();
        }
      };
    }
    if (!empty(($node->get('field_challeng_subpage_url_3')->getValue()[0]['value'])) && ($node->get('field_challenge_subpage_enable_3')->getValue()[0]['value'])) {
      $friendly_subpage_url = clean_url($node->get('field_challeng_subpage_url_3')->getValue()[0]['value']);
      $node->set('field_challeng_subpage_url_3', $friendly_subpage_url);

      db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/' . $friendly_subpage_url)->execute();

      if ($node->getTranslation('fr')->get('field_friendly_url')->getValue() && $node->getTranslation('fr')->get('field_challeng_subpage_url_3')->getValue()) {
        if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_3')->getValue()[0]['value'])) {
          db_insert('url_alias')->fields([
            'source' => '/challenges/' . $node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_3')->getValue()[0]['value'],
            'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_3')->getValue()[0]['value'],
            'langcode' => 'fr',
          ])->execute();
        }
      };
    }
    if (!empty(($node->get('field_challeng_subpage_url_4')->getValue()[0]['value'])) && ($node->get('field_challenge_subpage_enable_4')->getValue()[0]['value'])) {
      $friendly_subpage_url = clean_url($node->get('field_challeng_subpage_url_4')->getValue()[0]['value']);
      $node->set('field_challeng_subpage_url_4', $friendly_subpage_url);

      db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/' . $friendly_subpage_url)->execute();

      if ($node->getTranslation('fr')->get('field_friendly_url')->getValue() && $node->getTranslation('fr')->get('field_challeng_subpage_url_4')->getValue()) {
        if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_4')->getValue()[0]['value'])) {
          db_insert('url_alias')->fields([
            'source' => '/challenges/' . $node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_4')->getValue()[0]['value'],
            'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_4')->getValue()[0]['value'],
            'langcode' => 'fr',
          ])->execute();
        }
      };
    }
    if (!empty(($node->get('field_challeng_subpage_url_5')->getValue()[0]['value'])) && ($node->get('field_challenge_subpage_enable_5')->getValue()[0]['value'])) {
      $friendly_subpage_url = clean_url($node->get('field_challeng_subpage_url_5')->getValue()[0]['value']);
      $node->set('field_challeng_subpage_url_5', $friendly_subpage_url);

      db_delete('url_alias')->condition('source', '/challenges/' . $friendly_url . '/' . $friendly_subpage_url)->execute();

      if ($node->getTranslation('fr')->get('field_friendly_url')->getValue() && $node->getTranslation('fr')->get('field_challeng_subpage_url_5')->getValue()) {
        if (!empty(get_url_alias('/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value']) . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_5')->getValue()[0]['value'])) {
          db_insert('url_alias')->fields([
            'source' => '/challenges/' . $node->getTranslation('en')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('en')->get('field_challeng_subpage_url_5')->getValue()[0]['value'],
            'alias' => '/defis/' . $node->getTranslation('fr')->get('field_friendly_url')->getValue()[0]['value'] . '/' . $node->getTranslation('fr')->get('field_challeng_subpage_url_5')->getValue()[0]['value'],
            'langcode' => 'fr',
          ])->execute();
        }
      };
    }
    else {
      // Do nothing.
    }
  }
}

function get_url_alias($customAlias) {

  $query = db_query("SELECT pid FROM url_alias WHERE alias =:alias", [':alias' => $customAlias]);

  $query->allowRowCount = TRUE;

  if ($query->rowCount() == 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

function clean_url($dirtyUrl) {
  $friendly_url = $dirtyUrl;
  $friendly_url = strtolower($friendly_url);
  $friendly_url = str_replace('&', '', $friendly_url);
  $friendly_url = str_replace(' ', '-', $friendly_url);
  $friendly_url = str_replace('--', '-', $friendly_url);

  return $friendly_url;
}

function get_friendly_url_name($urlName) {
  $query = db_query("SELECT * FROM node__field_friendly_url WHERE field_friendly_url_value =:field_friendly_url_value", [':field_friendly_url_value' => $urlName]);

  $query->allowRowCount = TRUE;

  if ($query->rowCount() == 0) {
    return FALSE;
  }
  else {
    return TRUE;
  }
}
