<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function challenge_pages_theme() {
  return [
    'challenge_pages_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-page-theme-page',
    ],
    'challenge_subpage_module_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-subpage-theme-page',
    ],
    'challenge_news_module_page_theme' => [
      'render element' => 'form',
      'template' => 'challenge-news-theme-page',
    ],
  ];
}
