name: 'PCO Cities Config Import'
description: 'Provides customizations'
type: module
core: 8.x
package: 'PCO CITIES'

# Required modules
#dependencies:
#  - drupal:lightning_page
#  - drupal:wxt_core
#  - drupal:wxt_ext_layout
